### ISSUE TITLE
Upgrade from 3.3.1 to 4.2

### ISSUE THREAD

**Issue by penguinawesome** [alexalok/dotAPNS#104]
Hi there! its been awhile, we saw that the latest version is now already at 4.2.

Is it safe to upgrade from 3.3.1 to 4.2? Or are there any breaking changes that we need to modify our code?

**Comment by alexalok** [comment]
Hi! 4.0 did indeed introduce a somewhat breaking change by adding a new exception thrown if ApnsClient is provided with an expired certificate. Please see [release notes](https://github.com/alexalok/dotAPNS/releases/tag/4.0.0) for more info.

**Comment by penguinawesome** [comment]
Thats cool! Is that the only breaking changes? I think we are good with that, we don't have any dependency on the exception being thrown since we just log it regardless of the output of the exception.

**Comment by alexalok** [comment]
This is the only breaking change so feel free to update. That said you should test that everything works after the update.
