### ISSUE TITLE
Thank you for a great API

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#108]
I started using your dotAPNS API when Apple switched to the new format because I wasn't smart enough to figure out that stuff on my own. Your API was a lifesaver for me, and I really appreciate your work on it. It has worked reliably for the several years I have been using it. It has also provided me an educational experience, from which I have learned new development tricks.

I also appreciate the help you gave me early on when I was climbing the learning curve.

I have been in software development in one form or another for nearly forty years, including assembly language for microcontrollers. As of last week, I am now retired, and I have turned my enterprise development functions over to a new developer, who has been apprised of your API. I am not sure he will need your help, since your dotAPNS has been so reliable, it will probably never give him any trouble,

At any rate, I will be unsubscribing from your email list, but not without making sure you know how much I appreciate your efforts and your help! Thank you again!

Bill

**Comment by alexalok** [comment]
Hi Bill,

thank you for the warm words! I'm glad that I and my library were of use for you. It's crazy that your professional experience is almost twice as much as my entire lifespan😮.  I wish you all the best in retirement. Have fun with your new free time!

Take care,
Alex
