### ISSUE TITLE
The SSL connection could not be established

### ISSUE THREAD

**Issue by yaj806** [alexalok/dotAPNS#110]
windows  server 2022

use [certificate-based] method,its return The SSL connection could not be established

use [token-based]  method,its ok

**Comment by alexalok** [comment]
dotAPNS supports certificate-based connection only on .NET Core 3.0 and above. Full .NET Framework and .NET Core 2.2 and below are not supported. See https://github.com/alexalok/dotAPNS/issues/6 for more info.
