### ISSUE TITLE
The SSL connection could not be established,

### ISSUE THREAD

**Issue by rkbsoftsolutions** [alexalok/dotAPNS#119]
**Describe the bug**
. I am getting "The SSL connection could not be established" on production. Sound like website need to SSL certificate. But Is any way to code will work without ssl configured.

**Environment**
OS name and version:  "Window Azure App service"
.NET version: .NET Core 3.1

**Comment by alexalok** [comment]
Please see https://github.com/alexalok/dotAPNS/issues/78#issuecomment-852858080 for a possible workaround

**Comment by rkbsoftsolutions** [comment]
@alexalok thanks for response. But "Window Azure App service" web application not providing any option "App Pool Identiy" like that. Could you please give me more insight, how we can do that?

**Comment by alexalok** [comment]
Sorry, I'm not familiar with Azure at all. Perhaps you could ask a more general question on StackOverflow, something along the lines of "making an http/2 request with client certificate fails on ..."

**Comment by rkbsoftsolutions** [comment]
@alexalok   I figured out the issue " X509KeyStorageFlags.MachineKeySet)" 
then restart /publish again application.
 it is working fine but only first call. 
When send second call it is getting failed.
Any Idea for same ?

**Comment by rkbsoftsolutions** [comment]
@alexalok  we should pass three flags when X509Certificate2 objects.
X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable

Then Looks working.

**Comment by rkbsoftsolutions** [comment]
It is in-consistent not working properly.

**Comment by rkbsoftsolutions** [comment]
@alexalok can i use "Polly" for try if connection get failed? I notice that code is maintaining "ConcurrentDictionary" dictionary. Will it impact on HttpClinet if we use "Polly"?

**Comment by alexalok** [comment]
> Will it impact on HttpClinet if we use "Polly"?

You should be able to use Polly without any difficulties. I have not however tested this setup.
