### ISSUE TITLE
AddSound for critical notifications

### ISSUE THREAD

**Issue by KrastianM2M** [alexalok/dotAPNS#126]
**Describe the bug**
The sound property beside form string can also be object for critical notifications

**Code snippet**
JSON preview of the sound field in the payload for a critical sound
"sound": {
      "critical" : 1,
      "name": "default", // or name of a sound file in the app's main bundle
      "volume": 1 // value between 0 (silent) and 1 (full volume)
    }

**Expected behavior**
AddSound method should also be able to receive a object

**Actual behavior**
AddSound only receives a string and there is no way to set a sound of the notification as critical.

**Additional context**
A critical sound plays even if Do Not Disturb is turned on or the device is muted.

**Comment by alexalok** [comment]
Hi @KrastianM2M!
Thank you for your suggestion. This feature is on my roadmap. Stay tuned for updates!

**Comment by phil16727** [comment]
Hi Alex,
We need this enhancement, any chance to prioritize this?

**Comment by alexalok** [comment]
> Hi Alex,
> We need this enhancement, any chance to prioritize this?
> 

Hi @phil16727,

Not at the moment. But I can find some free time to review a PR should one open.

**Comment by phil16727** [comment]
@alexalok 
That would be great! This shouldn't take long I think! Thank you so much!

**Comment by phil16727** [comment]
@alexalok 
I added the Sound myself. Would you be so kind to allow me to add a new Branch to the repo? Then you can check out my changes.

Remote: Permission to alexalok/dotAPNS.git denied to phil16727.
Fehler beim Übertragen per Push an das Remoterepository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/alexalok/dotAPNS.git/': The requested URL returned error: 403_

**Comment by phil16727** [comment]
Hi @alexalok could you please add me?

**Comment by alexalok** [comment]
Greetings @phil16727,

sorry for the late reply. May I ask you to fork my project and push changes there? This way we can arrange a PR later. Please check out [this short walk-through](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#propose-changes-to-someone-elses-project) on how to fork someone's repo to propose changes.

**Comment by phil16727** [comment]
@alexalok please check out my changes!

**Comment by phil16727** [comment]
After more testing, this is working fine without my changes! 
Please close the issue!

In order to work with critical Notificaiton AddCustomProperty("interruption-level", "critical", true); to you Push Message Payload.

**Comment by alexalok** [comment]
@phil16727,

very sorry for the delay. I am glad you were able to resolve the issue!
