### ISSUE TITLE
Cannot update to 4.4.0 because of a constraint: System.Net.Http.WinHttpHandler (= 5.0.0)'.

### ISSUE THREAD

**Issue by tom-andraszek** [alexalok/dotAPNS#127]
**Describe the bug**
Getting an error in Visual Studio 2022 when trying to update the dotAPNS NuGet package from 4.2.0 to 4.4.0:
Unable to resolve dependencies. 'System.Net.Http.WinHttpHandler 8.0.0' is not compatible with 'dotAPNS 4.4.0 constraint: System.Net.Http.WinHttpHandler (= 5.0.0)'.

**Comment by AnisTigrini** [comment]
You should maybe try updating to 4.2.1 or 4.3.0 to see wich relase is causing the problem.
4.4.0 is only code changes and has not package upgrade.
Looks like he droped support for netcoreapp 3.0 in relase 4.3.0 so you might need to update your project dotnet version.

**Comment by alexalok** [comment]
fixed in v4.4.1
