### ISSUE TITLE
TooManyProviderTokenUpdates or InvalidProviderToken or Unregistered

### ISSUE THREAD

**Issue by Rukid** [alexalok/dotAPNS#128]
I periodically started receiving errors like InvalidProviderToken, etc. All connections are unique to (BundleId, CertContent, KeyId, TeamId) and lives for the life of the entire application. The application also runs on multiple pods. Any ideas on what these errors are related to?
Connection creation:
![image](https://github.com/alexalok/dotAPNS/assets/10230209/73402aeb-f1b5-495d-acc3-5aa624e0a900)

**Comment by alexalok** [comment]
Is it possible to try the [ASP.NET Core integration](https://github.com/alexalok/dotAPNS?tab=readme-ov-file#dotapns-aspnet-core-integration) just to rule out any potential issues in your caching solution? It seems really strange especially considering that the integration itself [uses concurrent dictionaries](https://github.com/alexalok/dotAPNS/blob/d4c2c2b8f36f5f040b1179f4bf1d2cc7e00e3f6e/dotAPNS.AspNetCore/ApnsService.cs#L25) under the hood for caching as well.

You also say that your application runs on multiple pods. Do they share the same IP? If so, I'm afraid a distributed JWT sharing is required, which is not something supported by the library atm.
