### ISSUE TITLE
MissingProviderToken

### ISSUE THREAD

**Issue by wahmedswl** [alexalok/dotAPNS#129]
**Describe the bug**
Tried the certificate-base authentication and getting the `MissingProviderToken` error. It seems like client certificate are not being sent according to https://github.com/alexalok/dotAPNS/issues/118 but that shouldn't be because running on .Net Core 6.0. Can this be the certificate itself? This seems like the public certificate only 

![image](https://github.com/alexalok/dotAPNS/assets/15020561/5624506b-d29d-4cc3-86c6-1247452c216a)

**Code snippet**
![image](https://github.com/alexalok/dotAPNS/assets/15020561/4d35605e-868c-4c13-8e85-988dbe499981)

**Expected behavior**

**Actual behavior**

**Environment**
OS name and version: *Windows 11*
.NET version: *.NET Core 6*
dotAPNS version:  *4.4.1*

**Additional context**

**Comment by alexalok** [comment]
`ApnsClient.CreateUsingCert` expects to find a .p12 certificate with a private key contained within it. This is how I do it on my Windows machine under WSL:

1. Generate cert request
`openssl req -newkey rsa:2048 -keyout universal.key -out universal.req -nodes`
2. Upload it to Apple Developer during APNs cert creation. 
3. Download cer file (public key) from Apple
5. Convert public key (cer) to pem format
`openssl x509 -inform der -in aps.cer -out universal.cer.pem`
6. Generate p12
`openssl pkcs12 -export -out universal.p12 -inkey universal.key -in universal.cer.pem`
