### ISSUE TITLE
How to set a custom aps object

### ISSUE THREAD

**Issue by Ghousepasha-ios** [alexalok/dotAPNS#130]
Hello

I would like to set a custom aps object like below.

`{
  'aps': {
    'event': 'update',
    'content-state': {
      'payload': {
        'aliasName': 'Location House',
        'AccountNumber': '(123445566)',
        'status': 2,
        'statusText': 'Completed',
        'title': 'ticket status'
      }
    },
    'timestamp': 1723119300
  }
}`

**Comment by alexalok** [comment]
Hey there!

I believe this method is what you are looking for: `ApplePush.AddCustomProperty(string key, object value, bool addToApsDict = false)`. You can use it like so:

```c#
ApplePush push = new ApplePush(ApplePushType.Alert)
    .AddCustomProperty("customPropertyKey", new { value1 = "123", value2 = 456 }, addToApsDict: true);
```

**Comment by Ghousepasha-ios** [comment]
@alexalok 
Yes, I found it here https://github.com/alexalok/dotAPNS?tab=readme-ov-file#or-to-the-aps-section.

Thank you
