### ISSUE TITLE
Support for anroid devices

### ISSUE THREAD

**Issue by feeleen** [alexalok/dotAPNS#132]
Do you plan to implement api to do pushes to android devices?

**Comment by alexalok** [comment]
Hey @feeleen,

No, there are no plans for dotAPNS to support anything but Apple Push Notification service. There is an official Firebase C# SDK that supports [sending pushes](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-specific-devices). Perhaps it could fit your requirements?
