### ISSUE TITLE
Question (not a bug)

### ISSUE THREAD

**Issue by molinch** [alexalok/dotAPNS#133]
Hey @alexalok 
Thanks for the awesome lib and accepting my PR the other day 👍 

I have a question regarding VoiP notifications.
Am I right that `AddImmediateExpiration` should be used in this case, or you'd suggest specifying an expiration manually via `AddExpiration`?

We're basically performing video calls, and of course they should appear on the device even if the app isn't running, and ASAP.

By the way do you suggest other configuration on the push notification for VoIP? (besides of course the token)

**Comment by molinch** [comment]
I read the Apple documentation ten times and it's pretty clear now:
- AddImmediateExpiration()
- AddContentAvailable()

Both are needed for VoIP

**Comment by alexalok** [comment]
Hi @molinch,

Glad to hear you were able to resolve the issue. I haven't touched VoIP for quite some time so I wouldn't be able to advise anyway. Thanks for sharing your findings!
