### ISSUE TITLE
HTTP request failed: System.Net.Http.HttpRequestException: Error while copying content to a stream.

### ISSUE THREAD

**Issue by Ghousepasha-ios** [alexalok/dotAPNS#134]
**Describe the bug**
Some notification are sending successfully, but some of the them receiving following error

**Code snippet**
Using `ApnsClient.CreateUsingJwt(client, options)`

**Expected behavior**
All notification should be sent, but some of them receiving this below error.

**Actual behavior**
![image](https://github.com/user-attachments/assets/cc6d9080-28eb-4ac4-aa67-c5c87a2d583e)

using .Net Framework 4.7

**Comment by alexalok** [comment]
Hi,

Can you please make sure that you are reusing the `ApnsClient` instance throughout the lifetime of your application? Repeated recreation of `ApnsClient` leads to rapid (i.e. more than once per 20 minutes) JWT regenerations which is explicitly forbidden by Apple.
