### ISSUE TITLE
MissingMethodException dotAPNS.ApnsClient dotAPNS.ApnsClient.CreateUsingJwt

### ISSUE THREAD

**Issue by eapeldoorn** [alexalok/dotAPNS#24]
Sending of push notification is done in a class library. Calling this library from a ASP.NET MVC application (.NET Framework 4.6.1) works. But when calling the library from a WEB API (.NET Framework 4.6.1) using Postman it is not working. It breaks on this line of code:

var apns = ApnsClient.CreateUsingJwt(new HttpClient(new WinHttpHandler()), options);

I see this in my log file:

System.MissingMethodException
  HResult=0x80131513
  Message=Methode niet gevonden: dotAPNS.ApnsClient dotAPNS.ApnsClient.CreateUsingJwt(System.Net.Http.HttpClient, dotAPNS.ApnsJwtOptions).
  Source=ML.DomainModel
  StackTrace:
   at ML.DomainModel.PushMessaging.PushNotificationLogic.<SendApnsNotification>d__3.MoveNext() in C:\Projects\Makelaarsland-FEA-Push\ML.DomainModel\PushMessaging\PushNotificationLogic.cs:line 166

**Comment by alexalok** [comment]
Could you please provide a minimal repro (i.e. a fully set up project but without any code specific to your application)? If this is possible, make sure to remove your JWT data. You can upload your project either as a separate github repository or simply email me at *contact(at)alexalok.me*.

**Comment by eapeldoorn** [comment]
Alex, I sent you a sample project. Actually, this projects works. Can the exception come from missing dependencies in my project?
I'll try to reinstall the NuGet package including all dependencies.

**Comment by alexalok** [comment]
Probably related to https://github.com/dotnet/runtime/issues/28826, I suggest to do the following:
1. Ensure that you have the latest version of [System.Net.Http](https://www.nuget.org/packages/System.Net.Http/) package, which is 4.3.4 at the moment of writing. While it is being implicitly referenced by dotAPNS itself I still suggest to add an explicit reference.
2.  Open *Web.config* and ensure that the following `dependentAssembly` do exist:

```
<dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
</dependentAssembly>
```
If it isn't or if its contents are different, replace them with the ones given above and clean/build project.

If the above doesn't help, try retargeting to .NET Framework 4.7.2 and checking whether the error still persists. 

Looking forward to your feedback.

**Comment by eapeldoorn** [comment]
Alex, I tried your suggestion and it is working! I updated the System.Net.Http NuGet package to 4.3.4 in my projects. The assemblybinding is changed to:

`<dependentAssembly>
<assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
</dependentAssembly>`

Push sent succesfully.

**Comment by alexalok** [comment]
I'm glad that you've managed to resolve the issue! Thanks for sharing the steps you've performed so that others could use them should they get stuck in a similar situation.
As this is not directly related to the library but rather to the underlying .NET package management system there's nothing more I could do.
