### ISSUE TITLE
Null exception when using CertFilePath

### ISSUE THREAD

**Issue by gregorosaurus** [alexalok/dotAPNS#25]
Hey there,

I'm getting an error when using the CertFilePath of the ApnsJwtOptions. 
I debugged through it and it looks like the code is doing some replacing on the options.CertContent, instead of the "certContent". 

This is where the certContent is read. 
```
if (options.CertFilePath != null)
{
      Debug.Assert(options.CertContent == null);
      certContent = File.ReadAllText(options.CertFilePath);   //certContent is read and saved to a local variable certContent
}
```

This is where the replace happens shortly after the if/else statement: (line 151 ApnsClient.cs)
```
 certContent = options.CertContent.Replace("\r", "").Replace("\n", "")
                .Replace("-----BEGIN PRIVATE KEY-----", "").Replace("-----END PRIVATE KEY-----", "");
//certContent is being set, but using the options? 
```

As you can see, options.CertContent is never set in the options. (As the documentation says, set one or the other, but not both - an exception is thrown if you try).  

A work around is to do the file read yourself into the Options.CertContent.  

Thanks!

**Comment by alexalok** [comment]
Hi and thanks for the report! I can confirm this is indeed a bug. The fix will be released ASAP.

**Comment by alexalok** [comment]
The NuGet package [v2.3.1](https://www.nuget.org/packages/dotAPNS/2.3.1) with the corresponding fix has been released. Thanks again for the report!

**Comment by gregorosaurus** [comment]
Awesome thank you!
