### ISSUE TITLE
Why not give a detailed example？

### ISSUE THREAD

**Issue by DNetORM** [alexalok/dotAPNS#27]
I have read it several times, but I don't know how to use it. I want to use P18 certificate and password to send information to Apple's interface. Why did I look for the code and didn't find an example? What's the point of your code

**Comment by DNetORM** [comment]
You should give an example, how to load the certificate file, the parameters of the certificate password, bring the payload format, and then call your push method, whether it is real data, it doesn't matter. please  show the detail process to others, I do not know how to use it for several times.

**Comment by alexalok** [comment]
>  how to load the certificate file

To create an APNs client instance using .p12 certificate you may use the following code:
```c#
var cert = new X509Certificate2("voip.p12");
var apns = ApnsClient.CreateUsingCert(cert);
```
Note that if you have the certificate in another format (i.e. not .p12) then you have to convert it before using. There's plenty instructions on the Internet on how to do that.

> the parameters of the certificate password

I do not quite get what do you mean by that. If you mean loading a password-protected certificate, then there's an overload of `X509Certificate2` that does just that: [X509Certificate2 (string fileName, string password)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.-ctor?view=netcore-3.1#System_Security_Cryptography_X509Certificates_X509Certificate2__ctor_System_String_System_String_).
Or you can just use `ApnsClient.CreateUsingCert(cert, "password")` ([source](https://github.com/alexalok/dotAPNS/blob/f96bddc4c4ec7bd52737dc18e4763c9378fdf485/dotAPNS/ApnsClient.cs#L203)).

> bring the payload format

There's indeed not much information about that in README. I recommend checking [tests file](https://github.com/alexalok/dotAPNS/blob/master/dotAPNS.Tests/ApplePush_Tests.cs) for examples. 
I can also assist you if you are more specific on what do you intend to send in the pushes.

> call your push method

```c#
var cert = new X509Certificate2("voip.p12");
var apns = ApnsClient.CreateUsingCert(cert);

var push = new ApplePush(ApplePushType.Alert)
    .AddAlert("title", "body")
    .AddToken("token");

var response = await apns.Send(push);
if (response?.IsSuccessful == true)
    Console.WriteLine("Alert push was successfully sent!");
else if (response?.IsSuccessful == false)
    Console.WriteLine("Cannot send push, error: " + response.ReasonString);
else if (response?.IsSuccessful == null)
    Console.WriteLine("Cannot send push because APNs service is unreachable.");
```

> I do not know how to use it for several times

You can reuse an `ApnsClient` instance as long as you need it.

**Comment by DNetORM** [comment]
Thanks. Apple's push wasted me three days. It's finally solved now.

**Comment by alexalok** [comment]
Glad I could help! Feel free to open a new issue should you have any further difficulties.
