### ISSUE TITLE
Support for apns-expiration in APNs request headers

### ISSUE THREAD

**Issue by denisp76** [alexalok/dotAPNS#31]
Dear,
it could be interesting support also notification's expiration date.
According to [documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1), It needs to add in the HttpRequestMessage the header 'apns-expiration' with a 'UNIX epoch date expressed in seconds (UT'').

Thanks,
Denis.

**Comment by alexalok** [comment]
Hey, @denisp76 !
Thanks for the heads up. I will definitely look into this tomorrow.

**Comment by denisp76** [comment]
Hi Alexalok,perfect! 
Only for test, I downloaded your code and try to do it. I think  it's quite simple:
In class ApnsJwtOptions.cs, I added ExpirationInHours:
 /// <summary>        /// Notification's expiration in hours .        /// </summary>        [CanBeNull]        public int ExpirationInHours        {            get => _expirationInHours;            set => _expirationInHours = value;        }        [CanBeNull]        int _expirationInHours;
Change the costructor of ApnsClient.cs adding this new parameters:
 ApnsClient([NotNull] HttpClient http, [NotNull] #if NET46                    CngKey #else                   ECDsa #endif                   key, [NotNull] string keyId, [NotNull] string teamId, [NotNull] string bundleId, int expirationInHours)    Then I added in the ApnsClient.Send method the new header:
  req.Headers.Add("apns-expiration", (Math.Floor(DateTime.Now.Millisecond / 1000d) + (60 * 60 * _expirationInHours)).ToString());

It seems work well! If I set this parameter to 0, the notification is not stored by APNS, and if the device is offline, it will never reached by notification, when it will come online again.
Best regards,Denis.


    Il giovedì 10 settembre 2020, 21:32:33 CEST, Alex <notifications@github.com> ha scritto:  
 
 


Hey, @denisp76 !
Thanks for the heads up. I will definitely look into this tomorrow.

**Comment by denisp76** [comment]
Hi Alex,
perfect! 
Only for test, I downloaded your code and try to do it. I think  it's quite simple:

In class ApnsJwtOptions.cs, I added ExpirationInHours:

```
 /// <summary>
/// Notification's expiration in hours .
/// </summary>
[CanBeNull]
public int ExpirationInHours {
     get => _expirationInHours;
     set => _expirationInHours = value;
}
[CanBeNull]
 int _expirationInHours;
```

Change the costructor of ApnsClient.cs adding this new parameters:

```
ApnsClient([NotNull] HttpClient http, [NotNull]
#if NET46
 CngKey
#else
 ECDsa
#endif 
key, [NotNull] string keyId, [NotNull] string teamId, [NotNull] string bundleId, int expirationInHours)
```

Then I added in the ApnsClient.Send method the new header:

`req.Headers.Add("apns-expiration", (Math.Floor(DateTime.Now.Millisecond / 1000d) + (60 * 60 * _expirationInHours)).ToString());
`

It seems work well! If I set this parameter to 0, the notification is not stored by APNS, and if the device is offline, it will never reached by notification, when it will come online again.

Best regards,
Denis.

**Comment by alexalok** [comment]
I've added support for the proposed feature to the https://github.com/alexalok/dotAPNS/tree/feat-apns-expiration branch. Could you please test it and confirm everything is working as expected?

One thing to notice is that the code you proposed sets expiration date for the whole APNs client instance, meaning all pushes sent though it expire at the same date. I believe it makes more sense to set expiration date explicitly on every push. 

## You can add an expiration date to a push as follows:
### For expiration in the specific date:
```c#
var now = DateTimeOffset.UtcNow;
var push = new ApplePush(ApplePushType.Alert);
push.AddExpiration(now);
```
### For immediate expiration (meaning APNs will try to send it only once):
```c#
var push = new ApplePush(ApplePushType.Alert);
push.AddImmediateExpiration();
```

**Comment by denisp76** [comment]
Wonderful! I will test it as soon as possible! --> Perfect work well!

Thx,
Denis.
