### ISSUE TITLE
Thread-id support

### ISSUE THREAD

**Issue by vorpalmace** [alexalok/dotAPNS#32]
Hello,

I'd like to add a "thread-id" field to the payload, but after reading the documentation and checking the source code I couldn't figure it out how to do it. Is there a way already to do this, or if there isn't, are there any plants to implement it?

Thanks,
Tamás

**Comment by alexalok** [comment]
Hello, Tamás!

You may use `ApplePush.AddCustomProperty` method, for example:
### To add the field to the root of the payload
```c#
var push = new ApplePush(ApplePushType.Alert)
.AddCustomProperty("thread-id", "123");
```
###  Or to the `aps` section
```c#
var push = new ApplePush(ApplePushType.Alert)
.AddCustomProperty("thread-id", "123", true);
```
An example can also be found [here](https://github.com/alexalok/dotAPNS/blob/72f23e74f81717968b7dfcc997660b105d8c3d63/dotAPNS.Tests/ApplePush_Tests.cs#L90).

Please feel free to reach out if you need more assistance!

Regards,
Alex

**Comment by vorpalmace** [comment]
Thank you for the quick reply! The aps example is exactly what I was looking for. Somehow I missed that AddCustomProperty has a third parameter.

Regars,
Tamás

**Comment by alexalok** [comment]
Glad I could help! I will provide more examples in the README to make this more clear :)
