### ISSUE TITLE
Bouncy Castle warning with NETCoreApp,Version=v3.1

### ISSUE THREAD

**Issue by agentschmitt** [alexalok/dotAPNS#34]
When i add dotAPNS.AspNetCore to my project i get this warning:
Warning NU1701: Package 'BouncyCastle 1.8.5' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. (NU1701)

Is it maybe possible to use the netcore package of bouncycastle? https://www.nuget.org/packages/BouncyCastle.NetCore/
Maybe you could add add .NETCoreApp as target to your app and use the dotnet core variant of the lib.

**Comment by alexalok** [comment]
Hey, @agentschmitt!

Thanks for bringing the attention to this issue. To be honest, I wasn't aware of the BouncyCastle.NetCore library existence. Of course it makes total sense to change the package. I will do this tomorrow. 
In the meantime you can safely use the .NET Framework BouncyCastle package and ignore the warning as all the methods from BouncyCastle used by dotAPNS are fully compatible with .NET Core.

**Comment by alexalok** [comment]
Upon further investigation I see that the BouncyCastle.NetCore package [page](https://www.nuget.org/packages/BouncyCastle.NetCore/1.8.6) links to its github [repo](https://github.com/chrishaly/bc-csharp) which hasn't been updated since 2018. 
Since there's really no issues with the original BouncyCastle package except the warning which in turn can be silenced I think it's reasonable to leave everything as it is.

**Comment by agentschmitt** [comment]
They BouncyCastle git project seems not to work on master. They seem to commit to release branches since 3 years. Last commit 6month ago to the 1.8.6 branch. But its also not a big issue to add a ignore for the warning of the package.
I just had to add it explicitly to the project to add an ignore on that to have zero warnings again :)

**Comment by alexalok** [comment]
I've added an explicit ignore for the warning in question [here](https://github.com/alexalok/dotAPNS/commit/87ed28746f5fa88a87024e84742d29270fc32c75). 
You may update your dotAPNS dependency to [2.5.1](https://www.nuget.org/packages/dotAPNS/2.5.1) to benefit from this fix.
Hope that helps! 👍
