### ISSUE TITLE
Making the Send method thread-safe

### ISSUE THREAD

**Issue by alexalok** [alexalok/dotAPNS#39]
The Send() method calls GetOrGenerateJwt() (source) which is in turn not thread-safe. As a result multiple JWT tokens may be created at the very beginning of push sending and/or when JWT token is recreated due to its expiration.

**Comment by penguinawesome** [comment]
This! Highly important :)

**Comment by penguinawesome** [comment]
Hi! Any updates? Lately we are encountering a lot of errors: Reason String: TooManyProviderTokenUpdates. I think this is due to the creating multiple JWT Tokens and using it concurrently. We are running in a multi thread (task.run) when sending notifs via APNS for higher throughput and scalability

**Comment by alexalok** [comment]
Hi @firephantomassasin,

please try https://github.com/alexalok/dotAPNS/tree/feat-threadsafe-send

Please don't forget to post the results here :)

**Comment by penguinawesome** [comment]
Hey looks great. It's working!

**Comment by alexalok** [comment]
Glad to hear!

I'll merge into master and publish a new .nuget package tomorrow if there aren't any signs of issues on your side.

**Comment by penguinawesome** [comment]
Sure! Looking forward to the new version in the nuget 👍  Thanks!

**Comment by penguinawesome** [comment]
Hello! how is the new nuget package update? :D

**Comment by alexalok** [comment]
Just uploaded: https://www.nuget.org/packages/dotAPNS/2.6.1

**Comment by penguinawesome** [comment]
So far so good, we are using the 2.6.1 in our production and we didn't encounter any TooManyProviderTokenUpdates errors so far. Thank you for this fix.
