### ISSUE TITLE
The deadline to upgrade to the APNs provider API has been extended to March 31, 2021.

### ISSUE THREAD

**Issue by i5kender** [alexalok/dotAPNS#42]
Hi,
Thank you for this beautiful library. I have .net framework 4.6 wcf service project and objective-c iOS mobile project. I have added this library to my wcf project and i can send notifications. 
**Do I need to make changes to my iOS project before the date (March 31, 2021) specified by the apple company?**

Best regards.

**Comment by alexalok** [comment]
Hello @i5kender,

thank you for the kind words :)
If you've migrated your project to use dotAPNS then you're ready for the changes you mentioned. The library itself does not use the legacy binary APNs connection and thus not affected by the deadline.
