### ISSUE TITLE
How to Handle Unsuccessful: Unregistered 

### ISSUE THREAD

**Issue by penguinawesome** [alexalok/dotAPNS#43]
Hi,

We encountered a lot of unsuccessful APNS with a reason of: Unregistered (it seems that this is a enum). Is there a way to retrieve the HTTP Status code that is being returned by the APNS Api? It would be better to include the HTTP Status code as well and also the raw message (not only the library ENUM).

Also what does this error mean: Reason: Unregistered | Reason String: Unregistered , and how do we handle this? Does this mean that the push token is not accessible anymore and we can safely delete this from our DB?

**Comment by alexalok** [comment]
Hello @firephantomassasin,

> Is there a way to retrieve the HTTP Status code that is being returned by the APNS Api?

Unfortunately there's no built-in method to do so as of now but you can refer to [ApnsResponseReason](https://github.com/alexalok/dotAPNS/blob/047a869e662158efa64f33da040eeef0f9bae379/dotAPNS/ApnsResponseReason.cs#L7) to deduct status code from the specific error reason.

As for the explanation of reasons, you may refer to the [official documentation on that matter](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/handling_notification_responses_from_apns). For `Unregistered` it says the following:

> The device token is inactive for the specified topic. There is no need to send further pushes to the same device token, unless your application retrieves the same device token...

Lastly, addressing your last question on 

> It would be better to include the HTTP Status code as well and also the raw message (not only the library ENUM).

As per the link above, the raw message only consists of the error reason and (optionally) the timestamp of when the token has become invalid. As such, there's nothing extra in the raw message itself that is not present in the [ApnsErrorResponsePayload](https://github.com/alexalok/dotAPNS/blob/master/dotAPNS/ApnsErrorResponsePayload.cs).
You may, however, access the raw error message by accessing the [ApnsErrorResponsePayload.ReasonRaw](https://github.com/alexalok/dotAPNS/blob/047a869e662158efa64f33da040eeef0f9bae379/dotAPNS/ApnsErrorResponsePayload.cs#L14) property.

**Comment by penguinawesome** [comment]
Thanks! Got it. In that case, the Reason field is already sufficient. 

Anyway, hmmm what is your suggestion on handling this kind of error? Can we can safely remove this Unregistered Push Token response from our DB? I hope you could add some suggestions on how to handle different kind of errors from APNS in the documentation :) That would be great. Thanks again.

**Comment by alexalok** [comment]
> what is your suggestion on handling this kind of error?

`Unregistered` means that the token is no longer usable and there's no way to fix that on your side, so you should delete it from DB.

> I hope you could add some suggestions on how to handle different kind of errors from APNS in the documentation

Yup, documentation definitely should be worked on :) 

Glad I could help!
