### ISSUE TITLE
System.net.http.winhttpexception a security error occurred Exception when using token-based authentication in ASP.NET app hosted in IIS

### ISSUE THREAD

**Issue by i5kender** [alexalok/dotAPNS#44]
Hi,
I have made a wpf test application and i can sent notification perfectly. I moved send notification method to my real wcf project.
I get an error from my wcf project as follows.
**Wcf project details**
-  .Net Framework 4.6 wcf service project. 
- Token-based connection

**Error info**
system.net.http.httprequestexception an error occurred while sending the request system.net.http.winhttpexception a security error occurred.
I also added screenshot of exception.

Best regards;

![natroHata_23_10_2020_12_49](https://user-images.githubusercontent.com/16920058/97003813-b004dc00-1544-11eb-9ad4-5b91849c26d8.PNG)

**Comment by alexalok** [comment]
Hello @i5kender,

Does the error appear every time you try to send the push or only from time to time?

**Comment by i5kender** [comment]
> Hello @i5kender,
> 
> Does the error appear every time you try to send the push or only from time to time?
@alexalok 
Yes, i get this error every time. 

**Note: the other application(WPF desktop app) is sending successfully each time.**

**Comment by alexalok** [comment]
Looks like certificate validation error ([ref](https://stackoverflow.com/questions/43265186/net-core-api-post-exception-gives-nativeerrorcode-12175)), you might want to check firewall/system proxy configurations. Other than that there's not much I can do really without the access to the machine you're having issues with.

**Comment by i5kender** [comment]
> Looks like certificate validation error ([ref](https://stackoverflow.com/questions/43265186/net-core-api-post-exception-gives-nativeerrorcode-12175)), you might want to check firewall/system proxy configurations. Other than that there's not much I can do really without the access to the machine you're having issues with.
@alexalok 
Let me also write where you threw the error. maybe more suggestions.

catch (HttpRequestException ex)
                    {
                        Console.WriteLine("Failed to send a push. HTTP request failed: " + ex);
                        apiMessage = "Failed to send a push. HTTP request failed: " + ex;
                    }

**Comment by i5kender** [comment]
Hi @alexalok,
We have activated TLS 1.2 and we allowed port 443 on the firewall but still the problem persists.

**Is there anything else I can try?**

Note: My web service is hosted by a hosting company. so I can not try the direct settings. 
I do the settings by opening a ticket.

Best regards;

**Comment by alexalok** [comment]
Are you using a VDS? If so, make sure you've got all the latest OS updates installed. 
Also, HTTP2 is only supported on Windows 7/Windows Server 2008 and above IIRC.

**Comment by i5kender** [comment]
Hi @alexalok,
HTTP/2 is only supported in Windows Server 2016 (IIS10) or above and Windows 10.
Talking to the hosting company, I learned that the my web service host on the windows 2012 server.
We realized that this error is not related to your library. 
https://stackoverflow.com/questions/48047398/send-http-2-request-on-windows-server-2012-r2

Thank you for your interest.

Best Regards.

**Comment by alexalok** [comment]
This is strange as IIS shouldn't even be involved in making the request. Are you sure you're using a [custom handler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) in the `HttpClient` you're passing to the `ApnsClient`?

Extract from the README:

> Once you've gathered all the information needed and created an options instance, it's time to call
> 
> ```c#
> var options = new ApnsJwtOptions() { ... };
> var apns = ApnsClient.CreateUsingJwt(new HttpClient(), options);
> ```
> 
> **Important:** when on .NET Framework, make sure that the `HttpClient` instance you pass to `CreateUsingJwt()` has a HTTP2 support. The default `HttpClient` **does not have it and will not work**. As a workaround it is suggested to install [System.Net.Http.WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) .nuget package and instantiate the `HttpClient` with this custom handler as follows: `new HttpClient(new WinHttpHandler())`.

**Comment by i5kender** [comment]
Especially I am using WinHttpHandler.

**Comment by alexalok** [comment]
Got it! 

Well, thank you for a thorough research. I'm closing the issue since there's nothing that can be done on the library side.

**Comment by i5kender** [comment]
Hi everyone, 
I have moved my web service project to Windows Server 2019 (IIS 10) then this problem solved and work perfectly. Thank you for your interest. @alexalok

Best Regards.

**Comment by alexalok** [comment]
Glad to hear you've figured that out!
