### ISSUE TITLE
Issue with SendAsync()

### ISSUE THREAD

**Issue by ThomasDevens** [alexalok/dotAPNS#45]
I'm currently trying to migrate away from PushSharp to support http/2 with sending apns notifications in my project. I was able to setup notifications within a test app (all done in .Net 4.6), but when trying to implement it within my actual app, I'm having issues with the SendAsync() function in the ApnsClient. It seems to make the request, and send the notification correctly, but it never returns a response (app just hangs after making the request). I've had similar issues to this with async tasks and solved it by adding ConfigureAwait(false) to the problem task, so I'm not sure if this is an issue with .Net (/something specific in my project), or if it should be changed within this package.

**Comment by alexalok** [comment]
Hi,

thanks for the report. You're right about the cause of the issue. I'll try to publish the fix tomorrow.

**Comment by ThomasDevens** [comment]
Awesome! Thanks for the quick response

**Comment by penguinawesome** [comment]
@ThomasDevens  are you using await when calling the apnsClient.Send method? How did you reproduce this kind of issue? We are kinda worried since we haven't encountered this kind of issue in our testing phase and production.

**Comment by alexalok** [comment]
@firephantomassasin this is a known issue when synchronously waiting on a task result with the captured synchronization context. 
If you haven't experienced this issue that means you're either not synchronously waiting for a task result or not using a synchronization context. 
WPF, for example, has the context and thus can be prone to this issue. 

While the correct fix for that is to not block on the task result, it is common to add `ConfigureAwait(false)` in the library code as a hacky fix. 

I can give you some references you can read if you're interested in this topic.

**Comment by alexalok** [comment]
Done in https://github.com/alexalok/dotAPNS/commit/f7e17d178cbb632dbc7f4d90ba16fb110263a3bb

Please update to [3.0.0](https://www.nuget.org/packages/dotAPNS/3.0.0)
