### ISSUE TITLE
APNs subtitles

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#46]
The APNs documentation indicates that push notifications may include a subtitle, in addition to the title and body. Is this something that can be added here? Thanks!

**Comment by alexalok** [comment]
Please check out the [3.1.0](https://www.nuget.org/packages/dotAPNS/3.1.0) version.

**Comment by BillInOKC** [comment]
Well done! Thank you!

**Comment by alexalok** [comment]
My pleasure! 👍
