### ISSUE TITLE
Apple Push Notification Port

### ISSUE THREAD

**Issue by phil16727** [alexalok/dotAPNS#47]
As stated in the Apple documentation the APNS has 2 Ports 443 as well as 2197. 
There should be a property for the port in order to switch between those two. 

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/

**Comment by alexalok** [comment]
Please check the version [3.2.0](https://www.nuget.org/packages/dotAPNS/3.2.0).

Call `apns.UseBackupPort();` to use port 2197.

**Comment by phil16727** [comment]
Great Thank you
