### ISSUE TITLE
Including emojis in push messages

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#48]
With the legacy APNs system, emojis could be added inline with the text using Java escape code values, i.e. "Here \uD83D\uDC49 is an emoji." With the new system, the notifications displays the undecoded string literal. Using dotAPNS, do I need to be doing it another way? Thank you again!

**Comment by alexalok** [comment]
Sending `Here \uD83D\uDC49 is an emoji.` results in

![image](https://user-images.githubusercontent.com/5950085/99095864-b4be2c80-25e6-11eb-8a74-e5db40c5a754.png)

So I guess that means no special handling is required :)

**Comment by BillInOKC** [comment]
OK, thanks. I must be doing something wrong.

**Comment by alexalok** [comment]
You should make sure to not escape the Unicode escape sequence itself, i.e. if `Here \uD83D\uDC49 is an emoji.` becomes `Here \\uD83D\\uDC49 is an emoji.` (notice the double backslashes) then the emoji is not shown.

**Comment by BillInOKC** [comment]
Thank you for your help with this. The string being sent is rendered just as shown, no escape characters (see below). Just for fun I tried it with two backslashes, and the notification was rendered with both of them. Here is how it's rendered with the original string:

![image](https://user-images.githubusercontent.com/73851028/99107078-e3b6ad00-25aa-11eb-891a-ecdc0918039b.png)

I'm not very good at this, so I am sure I am overlooking something. I just know that with the legacy APNs system, the emojis displayed as they should with the unicode in line with the text. I had assumed that in the new APNs, something had changed.

I really do appreciate your help with this, but I would not want to take your time away from your work.

EDIT: I am running the latest version of iOS.

**Comment by alexalok** [comment]
Could you past the extract from the code that is responsible for the push creation? I might help you with this.

**Comment by BillInOKC** [comment]
I am always reluctant to share my code because I am not very good at it and I am sure that experts such as yourself could find ways to improve it, but here it is. Also, it's in VB:

```
Private Sub Button1_Click(sender As System.Object, e As System.EventArgs) Handles btnTest.Click	'This is a test button
        Common.SendEventNotifications("Title", "", "Here \uD83D\uDC49 is an emoji.")
End Sub

```

'"Common" is a separate shared class that contains subs and functions that are accessed from a number of other classes in the project.

```
Shared Sub SendEventNotifications(strTitle As String, strSubTitle As String, strMessage As String)
        If My.Settings.bitSendEventNotificationsToDeveloper Then
            Dim tblDevRecipients As DataTable = GetDevDistro() '*****This retrieves a list of all of the iOS devices that I use for testing, not necessarily for sandbox use.
            Dim tblDeviceTokens As DataTable = GetTable("Select * from DeviceTokens")
            For Each row As DataRow In tblDevRecipients.Rows
                Dim dicAPNS As New Dictionary(Of String, String)
                Dim strDeviceToken As String = tblDeviceTokens.Select("UserName='" & row("Name") & "'")(0)("DeviceToken")
				
                'If the notification is going to a development iPhone, the system needs to know if it needs to use the Sandbox:
		Dim strIsDev As String = tblDeviceTokens.Select("UserName='" & row("Name") & "'")(0)("IsDev").ToString.ToLower
				
               	'We place all notification parameters into a data dictionary to send to the dotAPNS interface.
		With dicAPNS
                    .Add("title", strTitle)
                    .Add("subtitle", strSubTitle)
                    .Add("body", strMessage)
                    .Add("token", strDeviceToken)
                    .Add("sound", "bell.wav")
                    .Add("isdev", strIsDev)
                End With				
            dotAPNS.TokenBasedConnection(dicAPNS)
            Next

        End If

    End Sub
```
'The APNS code that interfaces with dotAPNS  is in a separate shared VB class named dotAPNS. Probably a little confusing:

```
Imports dotAPNS
Imports System.IO
Imports System.Net.Http
Imports System.Threading.Tasks

Public Class dotAPNS
	Shared Async Function TokenBasedConnection(dicAPNS As Dictionary(Of String, String)) As Task (Of string) 'dedicated to Andrew Norman for his invaluable help	
	'This is the interface to the dotAPNS API. I still haven't quite figured out how to make it work as a function, so it is essentially a function acting as a sub
	
        Dim intReason As Integer = 0
        Try
            Dim httpHandler As New WinHttpHandler
            AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", False)	'I'm not sure if I am using this correctly.
            httpHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12
            Dim httpclient As HttpClient = New HttpClient(httpHandler)
            If dicAPNS.ContainsKey("badge") Then
                If String.IsNullOrEmpty(dicAPNS("badge")) Or Not IsNumeric(dicAPNS("badge")) Then
                    dicAPNS("badge") = "0"
                End If
            Else
                dicAPNS.Add("badge", "0")
            End If

            Dim APNSoptions As New ApnsJwtOptions
            Dim strCertContents As String = File.ReadAllText(My.Settings.APNSAuthKeyFilename)

            With APNSoptions
                .BundleId = My.Settings.APNSBundleID
                .CertContent = strCertContents
                .KeyId = My.Settings.APNSKeyID
                .TeamId = My.Settings.APNSTeamID
            End With
            
            Dim APNS = ApnsClient.CreateUsingJwt(httpclient, APNSoptions)
			
            If dicAPNS("isdev") = "true" Then
                APNS.UseSandbox()
            End If
			
            Dim push As New ApplePush(ApplePushType.Alert)
            Dim strTitle As String = ""
            If dicAPNS.ContainsKey("title") Then strTitle = dicAPNS("title")

            Dim strSubtitle As String = ""
            If dicAPNS.ContainsKey("subtitle") Then strSubtitle = dicAPNS("subtitle")

            Dim strBody As String = ""
            If dicAPNS.ContainsKey("body") Then strBody = dicAPNS("body")

            '***************
            '.AddAlert format:[Title],[Subtitle],[Body]. If [title] or [subtitle] is left out or is an empty string, it is ignored. 
            '***************
			
            With push
                .AddAlert(strTitle, strSubtitle, strBody)
                .AddToken(dicAPNS("token"))
                .AddSound(dicAPNS("sound"))
                .AddBadge(CInt(dicAPNS("badge")))
            End With
			
            Dim ApnsResponse As ApnsResponse = Await APNS.SendAsync(push)	'This is the entry point to the dotAPNS API.
			
            Server.txtSystemMessages.AppendText("APNS: " & ApnsResponse.Reason.ToString & vbNewLine)
        Catch ex As Exception
            Server.txtSystemMessages.AppendText("APNS: " & ex.Message & vbNewLine)
        End Try

    End Function
```

I hope this makes sense. Again, thank you for your help with this.

**Comment by alexalok** [comment]
Oh, I see now. Perhaps the old binary protocol interpreted pieces of text that *look like* Unicode escape sequences. The new HTTP/2 protocol indeed does not do that. 
The reason it doesn't work for you is because VB does not support escape sequences, i.e. `\uD83D\uDC49` is treated as an actual UTF-8 character in C# but for VB it's just a regular text and is being sent to APNs as such.

Please refer to [this StackOverflow answer](https://stackoverflow.com/questions/3144053/how-to-represent-unicode-character-in-vb-net-string-literal) for possible workarounds.

**Comment by BillInOKC** [comment]
Thank you VERY much. The function `Char.ConvertFromUtf32(n)` shown in that post looks like it will do the trick. And it makes my code a little bit less complicated. Hopefully I won't need to bother you again!

**Comment by alexalok** [comment]
Glad I could help! Don't hesitate to ask should you have any difficulties in the future.
