### ISSUE TITLE
Mono support status

### ISSUE THREAD

**Issue by alexalok** [alexalok/dotAPNS#5]
Current status on how dotAPNS works on Mono:

- [ ] ~`Apns.CreateUsingCert()`~ - doesn't work due to a different X509Certificate2.Subject property handling. It doesn't include `0.9.2342.19200300.100.1.1=...` extension as it does on .NET Framework and .NET Core.
- [ ] ~`Apns.CreateUsingJwt()`~ - doesn't work, throws `NotImplementedException` somewhere in this method.

Since I don't use Mono and do not have resources to debug and test it, for library to support Mono an invested collaborator is required. Everyone is more than welcome to work on this.

**Comment by alexalok** [comment]
If the issue gets an external interest, I'll reopen it right away.

**Comment by mla1** [comment]
JFYI, it appears System.Security.Cryptography.ECDsa as well as PKCS#8 parsing is not supported in mono, see https://github.com/mono/mono/blob/master/mcs/class/referencesource/System.Core/System/Security/Cryptography/ECDsa.cs and https://github.com/mono/mono/issues/18821.

I used BouncyCastle to load the key and sign the token, but unfortunately I couldn't make HTTP/2 work under mono.
Here's the code if anyone is interested https://github.com/mla1/dotAPNS/commit/3de2911d71175d19738b3e44d532dda84fc1f869
