### ISSUE TITLE
Not Returning Response After Calling SendAsync

### ISSUE THREAD

**Issue by Pandurangv** [alexalok/dotAPNS#51]
I have tried using below option but not receiving any response. Please assist me what is going wrong

string certpath=@"F:\MyApplication\dotAPNS-master\ABMS_Distribution_Push_Notification_Certificate.p12";
            string pass="XXX";
            //var jwtOpt = new ApnsJwtOptions()
            //{
            //    BundleId = bundleid,
           //     CertFilePath = p8privateKey,
           //     KeyId = p8privateKeyId,
           //     TeamId = TeamId
           // };
            //var client = ApnsClient.CreateUsingJwt(new HttpClient(), jwtOpt);
            var client = ApnsClient.CreateUsingCert(certpath, pass);
            Task<ApnsResponse> sCode = Task.Run(async () =>
            {
                Console.WriteLine("Start 1");
                var push = new ApplePush(ApplePushType.Alert)
                    .AddAlert("title", "body")
                    .AddToken("AAAA");
                Console.WriteLine("Start 2");
                var response = await client.SendAsync(push);
                return response;
            });

**Comment by Pandurangv** [comment]
@jboehle @alexalok @MaximilianAst Please help me

**Comment by MaximilianAst** [comment]
Which runtime are you using? netcore 2.1, 3.1, net462?

**Comment by Pandurangv** [comment]
> Which runtime are you using? netcore 2.1, 3.1, net462?

I am using 3.1

**Comment by Pandurangv** [comment]
I am using windows 8.1 and I don't know Is it support http2

**Comment by MaximilianAst** [comment]
when your're compiling for netcore3.1 or higher http2 should work. Did the `ApnsClient.CreateUsingJwt(new HttpClient(), jwtOpt);` work before?

Also what is the content of `response`, if you make a breakpoint on `return response;` does it hit?

**Comment by Pandurangv** [comment]
> when your're compiling for netcore3.1 or higher http2 should work. Did the `ApnsClient.CreateUsingJwt(new HttpClient(), jwtOpt);` work before?
> 
> Also what is the content of `response`, if you make a breakpoint on `return response;` does it hit?

That also not worked and not returning not hit return response;

**Comment by MaximilianAst** [comment]
then what is the code around your snippet? It either seems like the thread exites before the push was sent or an uncatched exception occurred in Task.Run(...)

Why do you need `Task.Run(...)` here anyway?

**Comment by Pandurangv** [comment]
> > when your're compiling for netcore3.1 or higher http2 should work. Did the `ApnsClient.CreateUsingJwt(new HttpClient(), jwtOpt);` work before?
> > Also what is the content of `response`, if you make a breakpoint on `return response;` does it hit?
> 
> That also not worked and not returning not hit return response;

@MaximilianAst  I checked with windows 10 and now It's working fine with both methods thanks for your help

**Comment by MaximilianAst** [comment]
@alexalok should I update the README this noon and add the info, that there are issues when used on windows 8.1 and lower?

**Comment by Pandurangv** [comment]
> @alexalok should I update the README this noon and add the info, that there are issues when used on windows 8.1 and lower?

**Comment by alexalok** [comment]
@Pandurangv, there most likely an exception happening. Since you're firing a new task and not awaiting on it, the exception is swallowed. You could investigate it using [Diagnostics Tools](https://devblogs.microsoft.com/visualstudio/snapshots-on-exceptions-while-debugging-with-intellitrace/) or by [setting up an unhandled exceptions handler](https://dotnetcodr.com/2014/02/18/exception-handling-in-the-net-task-parallel-library-with-c-a-safety-catch-all/). 
If you're willing to do so, please reopen the issue. This would help us make the library better.

@MaximilianAst, thanks for the initiative! I think we should definitely update the README but only when we've found out the cause of the issue.

**Comment by Pandurangv** [comment]
@MaximilianAst 
I have checking same with adding log on windows server 2012 R2. 
Microsoft already mentioned at below Url. Http Support only on Windows 10. Windows Server 2016.
https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis

On windows server 2012 we are facing below exception can you assist me. Is It possible on windows server 2012 R2. If yes then how It can be achieve.

Exception
An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.

**Comment by MaximilianAst** [comment]
Are you hosting your application within IIS or as a standalone process?

All references I found are in combination with IIS:
- https://serverfault.com/questions/871501/windows-server-2012-r2-iis-10-http-2
- https://stackoverflow.com/questions/48047398/send-http-2-request-on-windows-server-2012-r2

> HTTP/2 is a rework of how HTTP semantics flow over TCP connections, and HTTP/2 support is present in Windows 10 and Windows Server 2016.

**Comment by Pandurangv** [comment]
> Are you hosting your application within IIS or as a standalone process?
> 
> All references I found are in combination with IIS:
> 
> * https://serverfault.com/questions/871501/windows-server-2012-r2-iis-10-http-2
> * https://stackoverflow.com/questions/48047398/send-http-2-request-on-windows-server-2012-r2
> 
> > HTTP/2 is a rework of how HTTP semantics flow over TCP connections, and HTTP/2 support is present in Windows 10 and Windows Server 2016.

Yes hosted on IIS

**Comment by alexalok** [comment]
> Exception
> An unhandled exception was thrown by the application.
> System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
> ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
> ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
> ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.

Looks like a TLS handshake problem to me. Could you try running outside of IIS and checking if the issue persists? If it does not, then it might be related to disabled cipher suites in IIS which in turn leads to an inability of your client and APNs server to decide on a common cipher suite. [IISCrypto](https://www.nartac.com/Products/IISCrypto/) might help you with that, though I advice to use it with caution because blindly enabling all checkboxes might leave your server vulnerable.

**Comment by MaximilianAst** [comment]
As @alexalok suggested, you could try publishing it as self-contained application and check if APNS are working when running as a console application to narrow down the issue.

**Comment by Pandurangv** [comment]
> Looks like a TLS handshake problem to me. Could you try running outside of IIS and checking if the issue persists? If it does not, then it might be related to disabled cipher suites in IIS which in turn leads to an inability of your client and APNs server to decide on a common cipher suite. [IISCrypto](https://www.nartac.com/Products/IISCrypto/) might help you with that, though I advice to use it with caution because blindly enabling all checkboxes might leave your server vulnerable.

@alexalok Yes I have tried but facing same error

**Comment by alexalok** [comment]
Sadly, that probably means HTTP/2 is either not supported on 2012 R2 network stack or has a bug when using client-side certificates. The best (and maybe the only) workaround would be to upgrade to a more recent Windows Server version. Not much can be done on the library side, unfortunately. I'll reflect that in a README.

**Comment by Pandurangv** [comment]
> Sadly, that probably means HTTP/2 is either not supported on 2012 R2 network stack or has a bug when using client-side certificates. The best (and maybe the only) workaround would be to upgrade to a more recent Windows Server version. Not much can be done on the library side, unfortunately. I'll reflect that in a README.

@alexalok Thanks for your valuable assistance
