### ISSUE TITLE
Badge-only alerts?

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#63]
I have tried to search this out on my own so I wouldn't trouble you with it, but I am having no luck. Under certain circumstances, I would like to send an alert that ONLY updates the badge, and not show an alert or play a sound. Is there a way to do that?

I've tried sending all blank fields except the badge field, and that didn't work. I also tried not adding the `.AddAlert` and the `.AddSound` parameters to the `push` command, and that didn't work.

Do you have any suggestions? Or is this just something that Apple doesn't allow?

Thanks!

**Comment by alexalok** [comment]
IIRC, `alert` type requires an alert body to be present (this is an APNs requirement).
You could try sending a `background` push, though I haven't tested it. You will also need to modify the library and comment out [this line](https://github.com/alexalok/dotAPNS/blob/69b18ac769bab6bab427d6bbde1b966b7256ed72/dotAPNS/ApplePush.cs#L175). With the modification done, try the following code:

```c#
new ApplePush(ApplePushType.Background).AddContentAvailable().AddBadge(123);
```

**Comment by BillInOKC** [comment]
As always, thanks for your help. Out of caution, I think I would rather avoid making any changes to your library code, and then having to compile it. This is not an important enough issue to take that kind of significant step. It's possible I can accomplish the same thing on the client side.

**Comment by alexalok** [comment]
For anyone else who stumbles on this issue, please remember that background pushes are unreliable and their delivery may be indefinitely delayed.
