### ISSUE TITLE
I would like to view the changelogs for every version released in nuget

### ISSUE THREAD

**Issue by penguinawesome** [alexalok/dotAPNS#65]
Hi! This library is very useful. Thank you for creating it. I would like to view the changelogs for every version released in nuget. Is there a changelog? I can't find it in the Tags / Release part of this github repo. Thanks!

**Comment by alexalok** [comment]
Hi! Thank you for kind words. Unfortunately there's no single central place for changelogs. You can however see the changes for every specific nuget release on its page on the nuget website.

**Comment by penguinawesome** [comment]
@alexalok maybe you could indicate some highlights  or summarize changelogs per version here in the github in the release page. Other libraries are putting their changelogs in the release page. This will be helpful for all users that are using the library, to see if there is a breaking changes or etc. Thanks again for the great work!


![image](https://user-images.githubusercontent.com/8090574/107597536-e1212d80-6c55-11eb-81c2-a15762525258.png)

**Comment by alexalok** [comment]
Yup, will try to do that. Thanks for the suggestion!

**Comment by penguinawesome** [comment]
Thanks @alexalok ! will wait for it. Currently we are still using the version 2.6.1, is it safe or are there any breaking changes when updating to the latest version 3.3.1?

**Comment by alexalok** [comment]
Generally it is always favorable to use the latest version. 

3.0.0 renames `Send` to `SendAsync` as per [Microsoft gidelines](https://docs.microsoft.com/en-us/dotnet/csharp/async#important-info-and-advice) and fixes possible deadlock in this method that existed in all previous versions. 

3.1.0 adds an alert subtitle support.

3.2.0 adds an APNs backup port support.

3.3.0 adds `apns-collapse-id` support and allows passing a cancellation token to `SendAsync`.

3.3.1 has no changes over 3.3.0 and was needed to fix some internal repo issues.

**Comment by penguinawesome** [comment]
Thanks! Will try to update to the latest version :)

**Comment by alexalok** [comment]
Will be done for the future versions on the [releases](https://github.com/alexalok/dotAPNS/releases) page.
