### ISSUE TITLE
Allow setting "UseSandbox()" on per-push basis

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#68]
Can you help me understand how to apply the `UseSandbox()` directive?

I have three iOS devices, one of which is a development device, which requires using the sandbox. When sending a push notification, my code checks to see if the target device is a development device (contained in the user database table). The process runs through this short segment:

`If dicAPNS("isdev").ToLower = "true" Then`
     `apns.UseSandbox()`
`End If`

(All Push data is sent to the Push method in a dictionary, dicAPNS.)

Which works fine. However, I'm finding that with any subsequent alerts, it continues to try to use the sandbox, and then returns an error for non-development devices. For it to work for all of them, I am having to make sure the development device is last on the list.

I should mention that often the push notifications are issued in a loop, sending each notification rapidly firing one right after another. I don't know how important that is to this issue.

Thanks!

**Comment by alexalok** [comment]
Hi,

this is indeed one of the shortcomings of the initial library design. For your scenario you would need to create two `ApnsClient` instances with one sending to production and another to sandbox. This is how I do it myself anyway.

I may rework that to allow setting environment on per-push basis but cannot provide estimates. Perhaps someone else could do that and send a pull request.

**Comment by BillInOKC** [comment]
OK, thanks... That's fine. I wouldn't have thought of having separate instances. That shouldn't be too difficult.

**Comment by alexalok** [comment]
Fixed in https://github.com/alexalok/dotAPNS/commit/30aa3f2bc8d52c4de2dfe80677d94e0b6829347f
