### ISSUE TITLE
Apple AAA Certificate

### ISSUE THREAD

**Issue by Woko12759** [alexalok/dotAPNS#69]
Today I received:
On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate.

I am using dotAPNS cause of HTTP/2 support. 
So, is there any further action needed, to integrate the AAACertificate which can be downloaded from Apple I have seen so far?

I am using PC...

Thanks!

**Comment by alexalok** [comment]
Hi,

were there any links in the message?

**Comment by alexalok** [comment]
Full extract:

From: Apple Developer <developer@email.apple.com>
> On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate. To ensure a seamless transition and to avoid push notification delivery failures, verify that both the old and new root certificates for the HTTP/2 interface are included in the Trust Store of each of your notification servers before March 29. 

> **Note that Apple Push Notification service SSL provider certificates issued to you by Apple do not need be to updated at this time.**

So to answer your question,

> So, is there any further action needed, to integrate the AAACertificate which can be downloaded from Apple I have seen so far?

This is the server-side APNs certificate so you generally don't need to do anything. dotAPNS uses your local PC's certificate store to validate the server certificate so just make sure your OS is up to date. For more info refer to [this article](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/).

**Comment by Woko12759** [comment]
Thanks for your answer:
But you said dotAPN uses your local PCs certificate store to validate.
So I have at least to install the new AAA certificate there, right?

**Comment by alexalok** [comment]
Proper root certificates should already be present in your OS installation. Generally, it's not advisable to install certificate by hand and let OS handle that instead.

**Comment by mubaraknet** [comment]
I'm using a Push Notification Server application based on C# using the dotAPNS library. I use the token-based APNS. Do I have any action items for this mail from Apple?

Sorry for asking this repeatedly, it's a little confusing :/

**Comment by alexalok** [comment]
> I'm using a Push Notification Server application based on C# using the dotAPNS library. I use the token-based APNS. Do I have any action items for this mail from Apple?

Generally no action is needed. Just make sure your OS has the latest root certificates. It's almost always the case if you update your system regularly.
