### ISSUE TITLE
Support FCM Push Notifs

### ISSUE THREAD

**Issue by penguinawesome** [alexalok/dotAPNS#70]
Hi! Thanks again for this great library. I hope FCM push notifs can be added in this library as well, to support the major mobile push notifs already. Right now we are still using different library just for FCM push (PushSharp), and it seems that pushsharp is still using the old FCM APIs.

**Comment by alexalok** [comment]
Hi! Unfortunately, as the library name implies, it only solves one specific task - sending pushes to the APNs. For FCM support other libraries should be used. Moreover, there's an [official FCM client](https://developers.google.com/api-client-library/dotnet/get_started) from Google.
