### ISSUE TITLE
when execute ApnsClient.CreateUsingJwt() have some issue

### ISSUE THREAD

**Issue by FelixSun** [alexalok/dotAPNS#75]
hi ， I have a issue in use the dll
In my pc , it's work 
but when I deployment the server ,there have some problem, 
the error when I execute this code" var apns = ApnsClient.CreateUsingJwt(httpClient, options)"
the error info like this: "the system cannot find the file specified"
I don't know what occur this issue, do you know?
If you have some idear, please tell me. thanks.

**Comment by alexalok** [comment]
Hi,

how do you create an `options` variable? If you specify the path to the certificate then make sure you do copy it to the server and that the path is valid both on your PC and on the server.
