### ISSUE TITLE
The SSL connection could not be established

### ISSUE THREAD

**Issue by wtlgo** [alexalok/dotAPNS#76]
I honestly not sure if this problem is related to the library or not and apologize a lot if it isn't, but I searched all the Internet today and couldn't find why this is happening and don't know where else to seek help.

So, here how I try to send the notification
```
            var opts =  new ApnsJwtOptions
            {
                CertFilePath = Path.Combine(Environment.CurrentDirectory, @"Certs\", "AuthKey_XXXXXXXXXX.p8"),
                BundleId = "xxx.xxxxxxxxx.xxxxxx",
                KeyId = "XXXXXXXXXX",
                TeamId = "XXXXXXXXXX"
            };

            var push = new ApplePush(ApplePushType.Alert).AddSound("1")
                .AddBadge(1)
                .AddCustomProperty("pushIx", hotelId)
                .AddCustomProperty("pushType", pushType)
                .AddToken(deviceToken)
                .AddAlert(null, message);

            var res = await _apnsService.SendPush(push, opts);
```

In the last line, the exception is thrown which states that
```
info: System.Net.Http.HttpClient.dotAPNS.ClientHandler[100]
      Sending HTTP request POST https://api.push.apple.com/3/device/xxxxxxxxxxxxxxxxxxxxxx

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
```

It's an ASP.Net Core project on .Net 5.
The system is Windows 8.1.
IDE is Visual Studio 2019 Community Edition.

What do I do wrong?

**Comment by alexalok** [comment]
Perhaps you could try on a different machine? Just to rule out the firewall/OS configuration problems.

**Comment by wtlgo** [comment]
Yes, seems like Windows 8 was the issue here. It works fine on Windows 10.

**Comment by iconsultWong** [comment]
But same error happen in Windows 2019 server

**Comment by alexalok** [comment]
> But same error happen in Windows 2019 server

Make sure your current OS allows for HTTP/2 requests. dotAPNS **requires** HTTP/2 networking stack on the system to be fully functional.
