### ISSUE TITLE
Not working on production server

### ISSUE THREAD

**Issue by JMPSoft** [alexalok/dotAPNS#79]
Hi Alexalok,
These codes are working  fine on developer computer. However, not working on production server. Even not giving any error message.
Could you please help. 
Thanks.

**Comment by alexalok** [comment]
Hi, 

you could try printing `response` contents. Unfortunately, it's not clear what the issue is.

**Comment by JMPSoft** [comment]
Thanks for your email. We will contact you as soon as possible.
www.jmpsoftware.co.uk

**Comment by JMPSoft** [comment]
Thanks Alexalok. It is okay after changing IIS Load User Profile.
