### ISSUE TITLE
Some times getting Error when call method apns.send()

### ISSUE THREAD

**Issue by Trushal0066** [alexalok/dotAPNS#82]
I am getting below error when call apns.send(). Can you please provide me solution for this ?

Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

**Comment by alexalok** [comment]
12007 is an error for ERROR_WINHTTP_NAME_NOT_RESOLVED. According to [MS Docs](https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages), this error indicates that *the server name cannot be resolved*. Looks like some kind of network issue, i.e. DNS request fails. 

I assume you use Windows, please try to execute the following commands in the cmd:

1. `nslookup api.development.push.apple.com`
2. `nslookup api.push.apple.com`

Do they both successfully return the IP addresses or do they/one of them fail? An example of a successful answer:

```
nslookup api.development.push.apple.com
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    api.sandbox.push-apple.com.akadns.net
Addresses:  17.188.138.71
          17.188.138.73
          17.188.138.70
Aliases:  api.development.push.apple.com
```
