### ISSUE TITLE
Getting BadDeviceToken when sending a push

### ISSUE THREAD

**Issue by michel-el-hajj** [alexalok/dotAPNS#84]
```
var options = new ApnsJwtOptions() { CertFilePath = "path", KeyId = "keyId", TeamId = "teamId", BundleId = "bundleId" };
var apns = ApnsClient.CreateUsingJwt(new HttpClient(new Http2CustomHandler()), options);
var push = new ApplePush(ApplePushType.Alert)
            .AddAlert(payload)
            .AddToken(deviceId);
var response =  apns.SendAsync(push).Result;
```

The goal is to send a PK push to initiate a VOIP Call.
I am getting BadDeviceToken when testing this code. i've read that it might be between production and development. How should i differentiate between development or production?
What might be the other cause?

**Comment by alexalok** [comment]
> How should i differentiate between development or production?

If you run a debug build (i.e. via xcode) then you have sandbox push/voip tokens and you need to call `apns.UseSandbox()` to make `ApnsClient` send sandbox pushes. 
Release build (i.e. the one you send to TestFlight or release on the AppStore) use production tokens. 
You have to differentiate the environments by hand, there is no built-in way to do so. Note that every time the environment changes you get new tokens from APNs even if it is the same device and an application.

Finally, to send VoIP push, you could use the following code:

```
var push1 = new ApplePush(ApplePushType.Voip)
    .AddVoipToken("voipToken");
```

Note that any other push types are delivered as a regular notification and do not invoke the application's delegate if it's in the background. Only `ApplePushType.Voip` is delivered as a VoIP notification and invokes the appropriate delegate in your application even if it's not running at all.

**Comment by michel-el-hajj** [comment]
Thanks for the reply, I edited the code as following and now i am getting this error DeviceTokenNotForThisTopic

```
var options = new ApnsJwtOptions() { CertFilePath = "path", KeyId = "keyId", TeamId = "teamId", BundleId = "bundleId" };
var apns = ApnsClient.CreateUsingJwt(new HttpClient(new Http2CustomHandler()), options);
apns.UseSandbox();
var push = new ApplePush(ApplePushType.Voip)
            .AddAlert(payload)
            .AddVoipToken(deviceId);
var response =  apns.SendAsync(push).Result;
```

**Comment by alexalok** [comment]
> i am getting this error DeviceTokenNotForThisTopic

This error indicates that the push certificate and bundle ID for your app are mismatched.

**Comment by michel-el-hajj** [comment]
The error was because i am using the fcm token used for normal push instead of the PK push token used for VOIP.
Thanks for the help.
This is my final solution in case someone needed it in the future:
```
var options = new ApnsJwtOptions() { CertFilePath = Certificate, KeyId = KeyId, TeamId = TeamId, BundleId = BundleId };
var apns = ApnsClient.CreateUsingJwt(new HttpClient(new Http2CustomHandler()), options);
if (Convert.ToInt32(IsProduction.ToString()) == 0)
{
    apns.UseSandbox();
}
var push = new ApplePush(ApplePushType.Voip)
.AddAlert(payload)
.AddVoipToken(deviceId);
var response =  apns.SendAsync(push).Result;
try
{
    var response =  apns.SendAsync(push).Result;
    if (response.IsSuccessful)
    {
        Console.WriteLine("An alert push has been successfully sent!");
    }
    else
    {
        switch (response.Reason)
        {
            case ApnsResponseReason.BadCertificateEnvironment:
                // The client certificate is for the wrong environment.
                break;
            // TODO: process other reasons we might be interested in
            default:
                Console.WriteLine("Failed to send a push, APNs reported an error: " + response.ReasonString);
                throw new ArgumentOutOfRangeException(nameof(response.Reason), response.Reason, null);
        }
    }
}
catch (TaskCanceledException a)
{
    Console.WriteLine("Failed to send a push: HTTP request timed out.");
}
catch (HttpRequestException ex)
{
    Console.WriteLine("Failed to send a push. HTTP request failed: " + ex);
}
catch (Exception e)
{
    Console.WriteLine(e.ToString());
}
```

**Comment by alexalok** [comment]
Glad to see you've had the issue resolved! Note that `ApnsClient` is meant to be reused. If you create a new one for every push you might encounter `TooManyProviderTokenUpdates` error.
