### ISSUE TITLE
Getting  "InvalidProviderToken"  while calling  sendAsync

### ISSUE THREAD

**Issue by Hiteshdprajapati** [alexalok/dotAPNS#85]
var options = new ApnsJwtOptions()
            {
                BundleId = "xxx.xxx",
                //CertContent = "",
                CertFilePath = @"path  of .p8",
                KeyId = "keyid",
                TeamId = "teamid"
            };
		 ApnsClient apns = ApnsClient.CreateUsingJwt(new HttpClient(new WinHttpHandler()), options);
                 var push = new ApplePush(ApplePushType.Alert)
                    .AddAlert("title", message)
                    .AddToken(device_token);

            var response = await apns.SendAsync(push);

**Comment by alexalok** [comment]
Please make sure KeyId and TeamId are set correctly and that the p8 certificate you're using is not revoked or expired.

**Comment by Hiteshdprajapati** [comment]
I  have  changed .p8 certificate and  its working  fine  now  
Thanks  @alexalok !!!

**Comment by alexalok** [comment]
Glad I could help!
