### ISSUE TITLE
Does this work in .NET Core 5?

### ISSUE THREAD

**Issue by nealculiner** [alexalok/dotAPNS#86]
Just implemented the code but it doesn't seem to work in asp.net core 5. Also of note is .NET Core 5 removes support for:

AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

**Comment by alexalok** [comment]
.NET 5 should be fully supported. Could you please elaborate on the issue you're facing? 

As for `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`, this is only needed when targeting .NET Core 2.0, 2.1 and 2.2.

**Comment by nealculiner** [comment]
I'm sorry but I abandoned the nuget and coded it myself. I'm using asp.net core 5
