### ISSUE TITLE
MDM push notification

### ISSUE THREAD

**Issue by lwdeveloper** [alexalok/dotAPNS#87]
Hi,

Is it possible to send the MDM push notification payload with dotAPNS?

In the format `{”mdm”:”PushMagicValue”}` which is the full message, not encapsulated in an "aps" object

We were previously able to do this with PushSharp but it has since stopped working, presumably due to the Apple HTTP/2 changes

An MDM certificate is also required to send the MDM messages which presumably shouldn't cause any issue with dotAPNS

Thanks for your time

**Comment by alexalok** [comment]
Hi!

Unfortunately, dotAPNS does not support MDM notifications as of now.

**Comment by lwdeveloper** [comment]
In case anyone else is following this, it is possible to send MDM push notifications with Azure Notification Hubs with a small workaround:

https://docs.microsoft.com/en-us/answers/questions/458207/azure-notifications-hub-ios-mdm-push-notifications.html?childToView=465023#answer-465023
