### ISSUE TITLE
getting bad device token error. 

### ISSUE THREAD

**Issue by digish777** [alexalok/dotAPNS#89]
getting bad device token error. I am not sure. what I am doing wrong. I am passing device token. I am passing certificate. Both are passing. Is it bundle id. if so. where to pass that?

**Comment by alexalok** [comment]
Are you sending a notification to a debug version of the app or a testflight/release one?

**Comment by MacFriis** [comment]
I have a similar issue, I'm using key/jwt token, but I'm running on debug on the device.
I have used this before with another backend implementing (Server side swift/ vapor), where it is working.

**Comment by alexalok** [comment]
> but I'm running on debug on the device.

Please make sure you're setting `ApnsClient` to [send sandbox pushes](https://github.com/alexalok/dotAPNS/blob/272a6332e98ee653b250635f568e362b09331994/dotAPNS/ApnsClient.cs#L280).
