### ISSUE TITLE
.Net Framework 4.7.2 Voip Token-based connection DeviceTokenNotForTopic

### ISSUE THREAD

**Issue by jasonItotal** [alexalok/dotAPNS#90]
I am using .Net Framework 4.7.2 with following code

List<string> deviceTokens = new List<string>();
deviceTokens.Add("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

var options = new ApnsJwtOptions()
{
    BundleId = "com.xxxxx.xxxxx.voip",
    CertFilePath = "AuthKey_xxxxxxxxxx.p8",
    KeyId = "xxxxxxxxxx",
    TeamId = "xxxxxxxxxx"
};
var apns = ApnsClient.CreateUsingJwt(new HttpClient(new Http2CustomHandler()), options);
var body = "{}";
var push = new ApplePush(ApplePushType.Voip)
                .AddAlert(body)
                .AddVoipToken("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
apns = apns.UseSandbox();
var response = await apns.SendAsync(push);

The response show DeviceTokenNotForTopic

I had use the same BundleId, CertFilePath, KeyId, TeamId and deviceToken in node-apn
and it is able to send the voip notification.

Do I miss some settings?

**Comment by alexalok** [comment]
Your `BundleId` is incorrect - please remove the `.voip` ending, it should be just an app bundle id with no additions. The library deduces the correct topic from raw bundle id automatically on a per-push basis. In your case, it likely ends up with the `com.xxxxx.xxxxx.voip.voip` topic, which is obviously incorrect.
