### ISSUE TITLE
Accept object as a alert

### ISSUE THREAD

**Issue by jasonItotal** [alexalok/dotAPNS#92]
When I sending voip alert, I need to send an object as following.
{
    uuid = "982cf533-7b1b-4cf6-a6e0-004aab68c503",
    incoming_caller_id = "0123456789",
    incoming_caller_name = "Tester"
}
Could the library provide a method to accept object as the payload.aps.alert?

Thanks.

**Comment by alexalok** [comment]
The only possible values for an `alert` object are listed [on the Apple Docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943365). Thus, this library does not support setting an arbitrary object as an alert.

You can however workaround this by force-adding an object using an `AddCustomProperty` method. Please see [README](https://github.com/alexalok/dotAPNS#custom-payload-fields) for more info and examples.
