### ISSUE TITLE
Getting error "'System.Dynamic.ExpandoObject' does not contain a definition for 'aps'"

### ISSUE THREAD

**Issue by snehalsomanis1** [alexalok/dotAPNS#93]
'System.Dynamic.ExpandoObject' does not contain a definition for 'aps'
 its throwing from library
Can someone help

**Comment by alexalok** [comment]
Please provide full stack trace and related code excerpt.

**Comment by snehalsomanis1** [comment]
Hi Alexa please find below stack trace

Stacktrace:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderController.SubmitError
Microsoft.CSharp.RuntimeBinder.Semantics.MemberLookup.ReportErrors
Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindProperty
Microsoft.CSharp.RuntimeBinder.RuntimeBinder.DispatchPayload
Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore
Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind
Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind
Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember
System.Dynamic.ExpandoObject+MetaExpando.BindGetMember
System.Dynamic.DynamicMetaObjectBinder.Bind
System.Runtime.CompilerServices.CallSiteBinder.BindCore
System.Dynamic.UpdateDelegates.UpdateAndExecute1
dotAPNS.ApplePush.GeneratePayload
dotAPNS.ApnsClient+<SendAsync>d__17.MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start
dotAPNS.ApnsClient.SendAsync
MobileInventoryService.Controllers.PushNotificationController.SendNotificationSKOM
MobileInventoryService.Controllers.PushNotificationController.SendNightlySyncApns
System.Web.Http.Controllers.ReflectedHttpActionDescriptor+ActionExecutor+<>c__DisplayClass6_2.<GetExecutor>b__2
System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync
System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start
System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsyncCore
System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsync
System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start
System.Web.Http.Controllers.ActionFilterResult.ExecuteAsync
System.Web.Http.ApiController.ExecuteAsync
System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__15.MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start
System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync
System.Net.Http.HttpMessageInvoker.SendAsync
System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync

**Comment by snehalsomanis1** [comment]
push = new ApplePush(ApplePushType.Alert);
   push.AddAlert(Title, "Test").AddBadge(1).AddSound("oven.caf");


            push.AddToken(deviceToken);
            push.AddCustomProperty("type", Type, true);
            push.AddCustomProperty("path", System.Text.RegularExpressions.Regex.Unescape(dbPath), true);
            push.AddCustomProperty("db-created-dt", DBCreatedDate, true);


            try
            {
                var response = apns.SendAsync(push);
                if (response.Result.Reason == ApnsResponseReason.Success)
                {
                    Console.WriteLine("An alert push has been successfully sent!");
                }
                else
                {
                    switch (response.Result.Reason)
                    {
                        case ApnsResponseReason.BadDeviceToken:
                            // The client certificate is for the wrong environment.
                            // TODO: retry on another environment
                            break;
                        // TODO: process other reasons we might be interested in
                        case ApnsResponseReason.TooManyRequests:
                            break;
                        case ApnsResponseReason.DeviceTokenNotForTopic:
                            break;
                        default:
                            throw new ArgumentOutOfRangeException(nameof(response.Result.Reason), response.Result.Reason, null);
                    }
                    Console.WriteLine("Failed to send a push, APNs reported an error: " + response.Result.ReasonString);
                }
            }
            catch (TaskCanceledException)
            {
                Console.WriteLine("Failed to send a push: HTTP request timed out.");
            }
            catch (HttpRequestException ex)
            {
                Console.WriteLine("Failed to send a push. HTTP request failed: " + ex);
            }
            catch (ApnsCertificateExpiredException)
            {
                Console.WriteLine("APNs certificate has expired. No more push notifications can be sent using it until it is replaced with a new one.");
            }

**Comment by alexalok** [comment]
If you just see it in Diagnostic Tools Events window then it's safe to ignore because it is thrown and caught internally by the CLR. Please reopen if the exception actually crashes your program.
