### ISSUE TITLE
Remind me: Token authorization means we do not need to renew APNS certificates?

### ISSUE THREAD

**Issue by BillInOKC** [alexalok/dotAPNS#94]
I've been using dot APNS for several months with AMAZING results. It has never failed.

Because it has been running flawlessly and not needed my attention for so long, I have forgotten some of the aspects of the token authorization-based system. I seem to remember that using this system means we do not need to renew the old-style APNS certificates with apple?

I received a reminder from Apple saying that the APNS certificate for one of my iOS apps was approaching expiration. I think I can just ignore that?

Thanks!

**Comment by alexalok** [comment]
Thank you for kind words! Certificates do indeed expire so you should renew them.
